language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/aaa6c6ae5ad874c7ab63
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always