language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
install:
  - npm install -g codecov
script:
  - npm test
  - npm run build
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/aaa6c6ae5ad874c7ab63
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always